import "dotenv/config";

export const env = {
  port: Number(process.env.PORT ?? 8787),
  host: process.env.HOST ?? "127.0.0.1",
  publicBaseUrl: process.env.PUBLIC_BASE_URL ?? "http://localhost:8787",
  executorWebhookUrl: process.env.EXECUTOR_WEBHOOK_URL,
  demoRepoMain: process.env.DEMO_REPO_MAIN ?? process.env.FINANCE_REPO_MAIN,
  signoffJobsDir: process.env.SIGNOFF_JOBS_DIR,
  signoffStateDir: process.env.SIGNOFF_STATE_DIR,
  redisUrl: process.env.REDIS_URL,
  browserbaseApiKey: process.env.BROWSERBASE_API_KEY,
  browserbaseProjectId: process.env.BROWSERBASE_PROJECT_ID,
  sentryAuthToken: process.env.SENTRY_AUTH_TOKEN,
  sentryOrg: process.env.SENTRY_ORG,
  sentryProject: process.env.SENTRY_PROJECT,
  githubToken: process.env.GITHUB_TOKEN,
  githubOwner: process.env.GITHUB_OWNER,
  githubRepo: process.env.GITHUB_REPO,
  githubAllowedOwner: process.env.GITHUB_ALLOWED_OWNER,
  githubAppSlug: process.env.GITHUB_APP_SLUG,
  githubAppId: process.env.GITHUB_APP_ID,
  githubAppClientId: process.env.GITHUB_APP_CLIENT_ID,
  githubAppClientSecret: process.env.GITHUB_APP_CLIENT_SECRET,
  githubAppPrivateKey: process.env.GITHUB_APP_PRIVATE_KEY,
  githubAppWebhookSecret: process.env.GITHUB_APP_WEBHOOK_SECRET,
  githubConnectionStateSecret: process.env.GITHUB_CONNECTION_STATE_SECRET,
  githubAppInstallationId: process.env.GITHUB_APP_INSTALLATION_ID,
  runnerSharedSecret: process.env.RUNNER_SHARED_SECRET,
  stripeSecretKey: process.env.STRIPE_SECRET_KEY,
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET,
  stripeCurrency: process.env.STRIPE_CURRENCY ?? "usd",
  stripeDefaultAmountCents: Number(process.env.STRIPE_DEFAULT_AMOUNT_CENTS ?? 2000),
};
